.gitignore
README.md
pom.xml
src/main/java/no/entur/uttu/export/blob/LocalDiskBlobStoreService.java
src/main/resources/application-local.properties
src/main/resources/db_init.sh
src/main/resources/logback.xml
src/test/java/no/entur/uttu/UttuIntegrationTest.java
src/test/resources/application-local.properties

Added a recipe for running uttu locally to the README.
Basically created a Spring application properties file for running locally, and made the spring-boot-maven-plugin use the `local` profile so that it picks up those application properties (and included how to do the same for running in IntelliJ in the README).

Make it easier to run uttu locally

---

src/main/java/no/entur/uttu/model/job/ExportLineAssociation.java
src/main/resources/db/migration/V8__On_delete_cascade_line_fkey_in_export_line_association.sql
src/test/groovy/no/entur/uttu/graphql/ExportGraphQLIntegrationTest.groovy

Deleting a line resulted in foreign key constraint violation on export line association. This adds a on delete cascade to the line foreign key, so that when a line is deleted, the export line association is also deleted.

WTK-222 Fix line deletion

---

src/main/java/no/entur/uttu/export/netex/producer/line/ServiceJourneyProducer.java

Operator refs in the export context are added to organisations in common file.

Add service journey operator refs to export context

---

src/main/java/no/entur/uttu/export/netex/producer/line/LineProducer.java
src/test/groovy/no/entur/uttu/graphql/AbstractFixedLinesGraphQLIntegrationTest.groovy
src/test/groovy/no/entur/uttu/graphql/ExportFixedLineGraphQLIntegrationTest.groovy

https://toil.kitemaker.co/cKEZAv-entur-ror/c1rxul-RoR_-_Development/items/1604
All notice assignments used "FlexibleLine" in the netex id ref, also for regular "Line". This bug was introduced when we added support for regular lines in uttu. The fix moves the production of notice assignemtns out of the common mapping logic into the visitor methods for the respective line types.
From export produced by new integration test:
```
<noticeAssignments>
<NoticeAssignment order="2" version="1" id="TST:NoticeAssignment:1">
<NoticeRef ref="TST:Notice:7b735783-73d0-46c3-8f9d-d4f202225cb4"/>
<NoticedObjectRef xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="LineRefStructure" ref="TST:Line:0bd86b87-7574-4bf0-867e-38b873eda5b3" version="0"/>
</NoticeAssignment>
</noticeAssignments>
```

Export produced incorrect refs for "fixed" lines in notice assignments

---

src/main/java/no/entur/uttu/export/netex/producer/line/ServiceJourneyProducer.java
src/main/java/no/entur/uttu/model/BookingArrangement.java
src/main/java/no/entur/uttu/model/FlexibleLine.java
src/main/java/no/entur/uttu/model/JourneyPattern.java
src/main/java/no/entur/uttu/model/Notice.java
src/main/java/no/entur/uttu/model/TimetabledPassingTime.java
src/main/java/no/entur/uttu/util/ValidationHelper.java
src/test/groovy/no/entur/uttu/graphql/AbstractFlexibleLinesGraphQLIntegrationTest.groovy
src/test/java/no/entur/uttu/model/BookingArrangementTest.java
src/test/java/no/entur/uttu/model/FixedLineTest.java
src/test/java/no/entur/uttu/model/FlexibleLineTest.java
src/test/java/no/entur/uttu/model/JourneyPatternTest.java
src/test/java/no/entur/uttu/model/NoticeTest.java
src/test/java/no/entur/uttu/model/ServiceJourneyTest.java
src/test/java/no/entur/uttu/model/TimetabledPassingTimeTest.java

Validation related fixes

---

src/main/resources/db/migration/V14__Use_time_no_timestamp_in_timetable.sql

https://docs.jboss.org/hibernate/orm/current/userguide/html_single/Hibernate_User_Guide.html#_localtime
The incorrect db type caused SQL error when moving integration tests to use testcontainers, possibly due to the testcontainers jdbc driver or the hibernate dialect being less lenient on type casting?
```
ERROR: invalid input syntax for type timestamp: "16:00:00+01"
```

fix: hibernate maps LocalTime to TIME

---

src/main/java/no/entur/uttu/model/TimetabledPassingTime.java
src/test/java/no/entur/uttu/model/ServiceJourneyTest.java

We currently have validation for the following
* No overlap in regular passing times, e.g. no departure from stop N after arrival at stop N+1, and no departure before arrival at the same stop, and so on.
* No overlap in time windows, e.g. no earliest departure after latest arrival at the same stop, and no overlapping time windows from one stop to the next.
What was missing was validation between regular passing time and time window. So this PR adds:
* There should be no overlap between time window in one stop and regular passing times in previous or next stop.

Add validation for combinations of regular passing times and time windows

---

src/main/java/no/entur/uttu/export/netex/producer/NetexObjectFactory.java
src/main/java/no/entur/uttu/export/netex/producer/common/MappedOperatingPeriod.java
src/main/java/no/entur/uttu/export/netex/producer/common/ServiceCalendarFrameProducer.java

Trying again after #185 failed with NPE
Background: In order to avoid confusion wrt the semantics of the time portion of dateTime in fromDate  and toDate of OperatingPeriod, use a ref to operating day instead which can refer to calendar date without time specification.
Example output:
```xml
<operatingDays>
<OperatingDay version="0" id="ENT:OperatingDay:1">
<CalendarDate>2023-04-17</CalendarDate>
</OperatingDay>
<OperatingDay version="0" id="ENT:OperatingDay:2">
<CalendarDate>2023-04-18</CalendarDate>
</OperatingDay>
</operatingDays>
<operatingPeriods>
<OperatingPeriod version="0" id="ENT:OperatingPeriod:1">
<FromOperatingDayRef ref="ENT:OperatingDay:1"/>
<ToOperatingDayRef ref="ENT:OperatingDay:2"/>
</OperatingPeriod>
</operatingPeriods>
<dayTypeAssignments>
<DayTypeAssignment order="1" …
```

Map operating periods to operating day refs

---

src/main/java/no/entur/uttu/export/netex/producer/common/FlexibleStopPlaceProducer.java

The id used to be the same as for its parent stop place, only changing the entity type. This does not work when you have multiple flexible areas in a stop place.

fix: Generate ids for flexible areas in export

---

src/main/java/no/entur/uttu/export/netex/producer/NetexObjectFactory.java
src/main/java/no/entur/uttu/export/netex/producer/line/JourneyPatternProducer.java
src/main/java/no/entur/uttu/export/netex/producer/line/LineProducer.java
src/main/java/no/entur/uttu/export/netex/producer/line/ServiceJourneyProducer.java

The attributes were added by the marshaller due to passing of subclass instances of VersionOfObjectRefStructure to the notice assignment object factory, which expected instances of VersionOfObjectRefStructure directly

fix: remove unneeded attributes from NoticedObjectRef element in export

---

src/main/java/no/entur/uttu/export/ExportService.java
src/main/java/no/entur/uttu/export/messaging/MessagingService.java
src/main/java/no/entur/uttu/export/messaging/PubSubMessagingService.java
src/main/java/no/entur/uttu/util/ExportUtil.java
src/test/java/no/entur/uttu/export/messaging/MessagingServiceTest.java

Use a variable name with timestamp for the NeTEx export generated by Uttu in order to simplify the validation pipeline.
Should be merged together with https://github.com/entur/marduk/pull/508

Use timestamped export file name

---

src/main/java/no/entur/uttu/export/netex/producer/NetexIdProducer.java
src/main/java/no/entur/uttu/export/netex/producer/NetexObjectFactory.java

Similar change previously: https://github.com/entur/uttu/pull/116
Perhaps we should look for a more generic solution 🤔 
Solves WTK-1828

fix: pad availability condition id with "_UTTU" to avoid id collision with other systems

---

src/main/java/no/entur/uttu/export/blob/LocalDiskBlobStoreService.java

Define a Spring profile that enables the local disk blob store implementation.
This can be used for local testing with authentication enabled.
(The existing profile "local" enables also the local disk blob store implementation, but disable authentication.)

Add local-disk-blobstore Spring profile

---

README.md

A few minor things I noticed while trying to get uttu (and enki) to run properly, plus a general formatting pass of the whole README to make it consistent with added hints in code blocks to allow for viewers to render the snippets with syntax highlighting.
fixes https://github.com/entur/uttu/issues/316
closes https://github.com/entur/uttu/pull/319

Documentation updates based on onboarding experience

---

pom.xml

- **adds [`spring-cloud-aws-starter-secrets-manager`](https://docs.awspring.io/spring-cloud-aws/docs/3.1.1/reference/html/index.html#spring-cloud-aws-secrets-manager)** which allows referencing secrets maintained in AWS Secrets Manager as part of normal Spring Boot application configuration as config imports
- **adds [`aws-secretsmanager-jdbc`](https://github.com/aws/aws-secretsmanager-jdbc)** which allows using credentials maintained in Secrets Manager as database connection parameters
**Motivation:**
In short, our AWS environment configuration relies on these libraries to keep secrets secret without inclusion in plaintext to project metafiles and also allow for keeping the configuration short :-)
Both of these libraries are visible in configuration only. As a pseudo example, these are …

add AWS Secrets Manager related libraries for use in application configuration

---

README.md

the [AWSpring](https://awspring.io/) project is a bit weird, the reason S3 autoconfiguration was enabled is because
- `spring-cloud-aws-starter-secrets-manager` depends on `spring-cloud-aws-starter`
- `spring-cloud-aws-starter` depends on `spring-cloud-aws-autoconfigure`
- and in `spring-cloud-aws-autoconfigure` exists [S3AutoConfiguration.java](https://github.com/awspring/spring-cloud-aws/blob/main/spring-cloud-aws-autoconfigure/src/main/java/io/awspring/cloud/autoconfigure/s3/S3AutoConfiguration.java) with
```java
@ConditionalOnClass({ S3Client.class, S3OutputStreamProvider.class })  // these are in classpath because we have manual S3 integration
@ConditionalOnProperty(name = "spring.cloud.aws.s3.enabled", havingValue = "true", matchIfMissing = true)
```
This might be worth filing an …

document how to prevent faulty activation of s3 autoconfiguration

---

src/main/java/no/entur/uttu/graphql/fetchers/CodespaceUpdater.java
src/main/java/no/entur/uttu/graphql/fetchers/ProviderUpdater.java

Noticed while developing custom auth solution for Fintraffic.

replace old style role checks with delegation to userContextService

---

pom.xml
src/main/java/no/entur/uttu/export/blob/S3BlobStoreRepository.java
src/main/java/no/entur/uttu/export/blob/S3BlobStoreRepositoryConfig.java
src/test/java/no/entur/uttu/export/blob/S3BlobStoreRepositoryTest.java

- makes stacktraces easier to read
- should solve at least some of the build instability issues; CRT client seems to have synchronization problems for APIs which respond too fast, which is the case with Localstack
- as bonus, configuring exact timeouts etc. for normal S3 client is a lot easier

rework S3BlobStoreRepository to use the more stable AWS S3 (non-async) client instead

---

pom.xml
src/ext/java/no/entur/uttu/ext/fintraffic/security/FintrafficSecurityConfiguration.java
src/ext/java/no/entur/uttu/ext/fintraffic/security/FintrafficUserContextService.java
src/ext/java/no/entur/uttu/ext/fintraffic/security/HttpClientException.java
src/ext/java/no/entur/uttu/ext/fintraffic/security/model/EntraTokenResponse.java
src/ext/java/no/entur/uttu/ext/fintraffic/security/model/Me.java
src/ext/java/no/entur/uttu/ext/fintraffic/security/model/VacoApiResponse.java
src/ext/java/no/entur/uttu/ext/fintraffic/security/model/VacoCompany.java

... which utilizes Microsoft's and Fintraffic's services for access management
- Includes hand-rolled MS Graph integration because the Microsoft provided libraries for working with Graph are waaaaay too complex for what we actually need to do.
- Adds [Methanol](https://mizosoft.github.io/methanol/) which is an excellent wrapper/feature add-on for Java's native HTTP client.
Certain details about VACO API are kept vague on purpose :-)

Fintraffic specific UserContextService

---

pom.xml
src/main/java/no/entur/uttu/export/ExportService.java
src/main/java/no/entur/uttu/export/blob/S3BlobStoreRepository.java
src/test/java/no/entur/uttu/export/blob/S3BlobStoreRepositoryTest.java

Include export metadata to objects when exporting.
This PR updates `rutebanken-helpers` to `2.33` which added support for object metadata injection (https://github.com/entur/rutebanken-helpers/issues/301) and reworks `ExportService` so that it always provides the metadata for the backing `BlobStoreRepository`. Metadata keys are prefixed with `no.entur.uttu.export.` to allow the consuming end to easily identify where the information originates from. Also enhances `S3BlobStoreRepository` to fully utilize this new functionality.

TIS-862/include export metadata for blobs

---

README.md
src/ext/java/no/entur/uttu/ext/entur/organisation/EnturLegacyOrganisationRegistry.java
src/main/java/no/entur/uttu/export/netex/producer/common/OrganisationProducer.java
src/main/java/no/entur/uttu/graphql/LinesGraphQLSchema.java
src/main/java/no/entur/uttu/graphql/fetchers/OrganisationsFetcher.java
src/main/java/no/entur/uttu/graphql/model/Organisation.java
src/main/java/no/entur/uttu/organisation/NetexPublicationDeliveryFileOrganisationRegistry.java
src/main/java/no/entur/uttu/organisation/spi/OrganisationRegistry.java
src/test/groovy/no/entur/uttu/graphql/AbstractFixedLinesGraphQLIntegrationTest.groovy
src/test/groovy/no/entur/uttu/graphql/AbstractFlexibleLinesGraphQLIntegrationTest.groovy
src/test/groovy/no/entur/uttu/graphql/AbstractGraphQLResourceIntegrationTest.groovy
src/test/groovy/no/entur/uttu/graphql/FlexibleLineGraphQLIntegrationTest.groovy
src/test/groovy/no/entur/uttu/graphql/NetworkGraphQLIntegrationTest.groovy
src/test/java/no/entur/uttu/export/netex/producer/common/OrganisationProducerTest.java
src/test/resources/fixtures/organisations.xml

Summary:
* Change model used for orgs from GeneralOrganisation to Authority and Operator
* Adds configurable overrides for exported authority and operator ids
Authority and operator IDs are exported according to the following logic:
* If a configured override exists for the organisation in question, use it;
* else if the organisation has a LegacyId with the appropriate type (Authority or Operator) use first occurence;
* else use the organisation id

Fix organisation exports

---

src/ext/java/no/entur/uttu/ext/fintraffic/security/FintrafficUserContextService.java

Adds caching to HTTP API calls made by `FintraffucUserContextService`, increases general timeouts by sixfold (5 -> 30 seconds) and in general contains some code restructuring to make it a tad cleaner.

Cache Fintraffic user context operations

---

README.md
docker-compose.yml

This adds OSRM server routing to the compose environment with instructions on how to package the image so that it can be used locally. The example is provided for convenience, and isn't how we actually do this, but it does serve as a baseline.
As one more note, the OSRM server with Norway data packaged and processed with it is about 3GB. This, and considering different users have different data needs is the main motivation why instructions for building the image are provided as manual step instead of further configuration at this point - obtaining the image might be wildly different to anyone using the routing functionality, and as the image sizes can be _very_ large, it's better to just assume this problem has been solved in some other way in the user's organization/architecture.

add routing profile for local development to docker compose

---

src/main/java/no/entur/uttu/graphql/LinesGraphQLSchema.java

Two different enums are used for transport modes, I chose the incorrect one here.

Swith to correct enum in schema

---

src/main/java/no/entur/uttu/graphql/LinesGraphQLSchema.java

Public code on line is optional in the nordic profile and in the database schema. We make it optional also in graphql to allow frontend to not set it. Use case is: When using branding, public code is not necessary.

Make public code nullable on line input type

---

src/main/java/no/entur/uttu/export/netex/producer/common/OrganisationProducer.java

If applied custom id to org during export, the original org object in the registry would be mutated, thus unable to look up in subsequent requests. The fix in this PR always makes a copy of orgs.

Fix: not allowed to mutate orgs from registry

---

pom.xml

Remove the configuration for downloading the PubSub emulator in unit tests.
This configuration is not needed since the default value set in the superpom is "true".
Support for downloading the PubSub emulator is deprecated for removal and being replaced by testcontainer.

Remove PubSub emulator configuration

---

src/main/java/no/entur/uttu/routing/osrm/OsrmService.java
src/test/java/no/entur/uttu/routing/osrm/OsrmServiceTest.java

When OSRM routing engine cannot find a route between two stops, the service now falls back to creating a straight-line route with accurate distance calculation using GeoTools GeodeticCalculator.
- Added createStraightLineRouteGeometry() method
- Added calculateDistance() using GeoTools orthodromic distance
- Updated error handling to use fallback instead of empty geometry
- Updated tests to expect straight-line routes on OSRM failures
Closes #614

feat: add straight-line fallback routing when OSRM fails

---

src/main/java/no/entur/uttu/error/codederror/FlexibleAreaValidationCodedError.java
src/main/java/no/entur/uttu/error/codes/ErrorCodeEnumeration.java
src/main/java/no/entur/uttu/export/netex/producer/line/JourneyPatternProducer.java
src/main/java/no/entur/uttu/graphql/fetchers/FlexibleStopPlaceUpdater.java
src/main/java/no/entur/uttu/graphql/mappers/FlexibleStopPlaceMapper.java
src/main/java/no/entur/uttu/model/ValidationResult.java
src/main/java/no/entur/uttu/service/FlexibleAreaValidationService.java
src/main/java/no/entur/uttu/util/Preconditions.java
src/test/java/no/entur/uttu/graphql/fetchers/FlexibleStopPlaceUpdaterTest.java
src/test/java/no/entur/uttu/service/FlexibleAreaValidationServiceTest.java

Validates that flexible area with type UNRESTRICTED_PUBLIC_TRANSPORT_AREA actually contain stops from stop place registry.
Validation is performed when saving the stop place itself, and when exporting lines that uses that stop place.
Closes #421

Add validation for flexible area with nsr stops
